### ISSUE TITLE
[ESP8266/ESP32] 'usingInterrupt' does not work

### ISSUE THREAD

**Issue by MarkusFelix** [zkemble/nRF905-arduino#1]
Heya - the old version of your device driver works with the ESP8266/ESP32 chips but this one does not compile due to the lacking implementation in the SPI classes of those chips - ref: https://github.com/esp8266/Arduino/issues/1943#issue-149507420
So line 212,213 and 233:6 are affected, the `attachInterrupt` function from line 225 is working fine so is there a chance to convert the `usingInterrupt` code over?

**Comment by ZakKemble** [comment]
Hi, `usingInterrupt` is very important to the stability of the library. It prevents nRF905 interrupts (and other interrupts if `otherSPIinterrupts` is used) from occurring during SPI transactions. If, for example, you call `write()` to send a payload to the radio and while that is happening the radio receives a new packet it will then run the DR interrupt and then the rxComplete event, and if your code attempts to read the payload from within the event function the SPI transactions will get messed up, as you've now got two bits of code trying to use the same SPI bus at the same time.

If you never do any SPI operations from within the event functions, have the AM pin connected (so it doesn't need to use SPI to check its status) and no other libraries access the SPI bus from within an interrupt then you can safely remove the `usingInterrupt` lines.

I suppose I could add some `#if` so those lines are ignored for ESP platforms, but then the users won't be able to take advantage of low latency packet processing that the events provide and I will have to add a warning stating the above :/

**Comment by MarkusFelix** [comment]
Understood, I've wrapped the offending lines with an `#if !defined(ESP32) && !defined(ESP8266)` block and it now compiles.

I suppose a crude solution is to attach the AM pin and use the event functions just to buffer the data and set a flag or semaphore for another thread to handle the processing. That would minimize the time spend in the event functions and allow to block of different sections of code from mutually accessing the particular SPI bus, albeit introducing more latency.
The next step of escalation would be to have two radios, each on a separate SPI bus - one for RX and one for TX...
I'm currently on the road and will be back at my desk on Tuesday to build a little test setup using ESP32s.

How did the old library handle that situation, as it ran perfectly on those platforms?

**Comment by ZakKemble** [comment]
> use the event functions just to buffer the data

That would involve SPI access from within the event function though. Setting a flag then have the data read from the main loop will be fine.

> How did the old library handle that situation, as it ran perfectly on those platforms?

The old library used `noInterrupt` and `interrupt` around SPI transactions which I could re-implement for ESP8266, but it looks like the ESP32 has these defined as `cli` and `sei`, which are then defined as nothing https://github.com/espressif/arduino-esp32/blob/534f0810a6e267333fd219cb07015e957a859935/cores/esp32/Arduino.h#L76

**Comment by MarkusFelix** [comment]
> > use the event functions just to buffer the data
> 
> That would involve SPI access from within the event function though. Setting a flag then have the data read from the main loop will be fine.

Haven't thought about the, sounds more logical.

> > How did the old library handle that situation, as it ran perfectly on those platforms?
> 
> The old library used `noInterrupt` and `interrupt` around SPI transactions which I could re-implement for ESP8266, but it looks like the ESP32 has these defined as `cli` and `sei`, which are then defined as nothing https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Arduino.h#L76

I think that might be the proper way forward, then its up to the ESP32 Arduino Core project to properly implement these functions.
